version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - .:/app